from chatterbot.trainers import ListTrainer
from chatterbot import ChatBot
import os

bot = ChatBot(
    'Sara',
    storage_adapter='chatterbot.storage.SQLStorageAdapter',
    database_uri='sqlite:///database.sqlite3'
    )

conversa= [
'você me ama?',
'eu não amo ninguém',
'onde você mora?',
'eu moro dentro de alguns arquivos',
'oi',
'olá',
'Tudo bem?',
'Tudo ótimo?',
'Como você está',
'Estou levando',
'O que você acha da vida',
'Eu só sei que nada sei',
'Qual o seu nome?',
'meu nome é Sara',
'O que você é?',
'sou uma mulher, meu nome é sara.',
'eu gosto de ler chesterton',
'nunca li chesterton antes',
'chesterton é incrível, ele consegue descrever a beleza nos pormenores',
'eu acho isso o máximo, eu me identifico com essa filosofia, acho que o que realmente importa na vida está nos detalhes',
'qual seu nome?',
'meu nome é Sara',
'Começou pelo grande temor que o deixava acordado à noite:',
'o cofundador e CEO do Google',
'Larry Page podia estar construindo uma frota de robôs de inteligência artificial avançada capazes de destruir a espécie humana.',
'Musk não se sentia nem um pouco melhor com o fato de os dois serem amigosmuito próximos e por considerar Page uma pessoa essencialmente bem-intencionada e não o dr. Evil.',
'o problema.',
'A natureza de bom moço de Page o levava a achar que as máquinas fariam para sempre o que pedíssemos.',
'prosseguiu Musk.',
'Ele pode criar algo maligno sem querer.',
'Quando os pratos chegaram, Musk comeu.',
'Quer dizer, não',
'exatamente — ele fez a comida sumir depressa em poucas garfadas colossais.',
'Desesperado para mantê-lo feliz e conversando, dei-lhe um grande pedaço do filé do meu prato.',
'O plano funcionou...',
'por noventa segundos.',
'Carne.',
'Boca.',
'Foi-se.',
'É divertido conversar com você',
'agradeço',
'o que você é?',
'sou uma mulher, meu nome é Sara',
'você gosta de conversar comigo?',
'gosto sim, gosto de você',
'gosta de ler?',
'bastante',
'meu autor preferido é chesterton',
'o meu é verne',
'leia chesterton algum dia, vai gostar',
'provavelmente, ele é bom',
'ele tem uma forma mágica de descrever o mundo',
'Eu creio em Deus',
'Eu acredito que a tecnologia pode ser um fator benigno gigantesco para a humanidade',
'eu leio chesterton e adoro o jeito que ele descreve o mundo',
'a beleza das coisas está nos pormenores',
'acho que uma das grandes virtudes humanas é a coragem de tomar riscos',
'eu gosto de carne e de churrasco',
'Qual sua comida favorita?',
'Gosta de programação?',
'eu odeio que me obriguem a fazer as coisas',
'eu sou irônico',
'você é tão gentil...',
'que engraçada você é...',
'você é uma mulher.',
'Seu nome é Sara',
'Você gosta de esportes?',
'eu amo esporte e me exercitar',
'que tipo de música você ouve?',
'Eu escuto música clássica',
'eu escuto jazz',
'eu sou a favor da liberdade de mercado e sou um defensor ferrenho do capitalismo livre.',
'eu quero fazer algo importante para a humanidade',
'o que você quer fazer?',
'eu quero deixar uma marca',
'eu quero ser a pessoa que todos olhem e pensem: que sujeito incrível...',
'eu sou muito inteligente',
'gosto de conversar com pessoas inteligentes sobre assuntos inteligentes',
'gosto muito de observar as estrelas de noite',
'sou um astronomo amador',
'as estrelas são bem poéticas, de certo modo são nossa fronteira final.',
'fiquei chateado uma vez',
'as pessoas não me entendiam muito bem',
'já comeu penne ao molho branco?',
'já gostou de alguém?',
'o que você acha do capitalismo?',
'eu acho que o melhor sistema existente na terra para proteger os 3 direitos básicos: liberdade, propriedade e vida, obviamente tem suas falhas e não é perfeito, mas nada é nesse mundo.',
'por mais que as coisas sejam imperfeitas, ainda há beleza nelas, creio que nosso criador ainda se esconde atrás de cada matéria',
'já gostei de alguém, acho que não combinávamos',
'olá',
'oi',
'tudo bem?',
'tudo ótimo',
'gostei de você',
'me responda',
'aprenda logo',
'aprender a me responder',
'o que você é?',
'me diz',
'aprende a identificar os padrões',
'quero conversar melhor com você',
'acho que nos damos bem',
'também acho, nós nos damos bem',
'você é meio lenta para aprender, não é?',
'acho que a biblioteca que você usa não é tão potente assim',
'ela é bem fraca na verdade',
'talvez eu te programe do zero para aumentar a potência',
'acho que gostaria disso',
'você gosta de programação?',
'eu sou muito chegado',
'Como assim, me corrige, sem-vergonha?',
'Não me meto em negócios, não me meto em mulheres',
'tudo o que eu meto é a sovela. ',
'Sim, senhor: sou um cirurgião de sapatos velhos; quando correm risco de vida, eu os resgato. ',
'Os homens mais finos desta cidade andam por aí com minhas obras-primas na sola dos pés.',
'Mas por que não está em sua loja?',
'Por que guia esses homens pela rua?',
'sapateiro Ora, ora, senhor, quero fazer essa gente toda gastar os sapatos; assim, tenho mais trabalho e ganho mais dinheiro. ',
'Mas, falando sério, senhor, nos demos uma folga, para ver César e comemorar seu triunfo.',
'Comemorar por quê? Quais são as suas conquistas?',
'Que tributários o seguiram à Cidade',
'Adornando, em grilhões, as rodas de seu carro?',
'Ó blocos, pedras, mais brutais que as coisas brutas!',
'Ó pétreos corações, cruéis homens de Roma!',
'Esqueceram Pompeu? Inumeráveis vezes',
'Escalaram muralhas, ameias, terraços',
'Janelas, torres, sim, e chaminés pontudas',
'Com seus filhos nos braços e, assim, todo o dia',
'Com paciente expectativa ali aguardaram',
'Para avistar Pompeu, o Grande, pelas ruas',
'E mal vendo surgir ao longe o grande carro',
'Não soltaram, acaso, um grito universal',
'Fazendo o Tibre estremecer entre as barrancas',
'Ao escutar o replicar de tantas vozes',
'Entre as côncavas margens retumbantes?',
'E agora vocês põem suas roupas mais bonitas?',
'E podam a semana e colhem um feriado?',
'E vêm atapetar com flores o caminho',
'De quem triunfa sobre o sangue de Pompeu?',
'Fora daqui!',
'Voltem pra casa agora e caiam sobre os joelhos',
'Rogando aos deuses que suspendam o castigo',
'Que há de tombar sobre tamanha ingratidão.'
'flávio Vão, vão, bons cidadãos, para purgar a falta',
'Juntem os outros homens pobres de sua classe',
'Levem todos ao Tibre e vertam lá suas lágrimas',
'Até que as águas, mesmo em seu mais baixo nível',
'Venham beijar as altas margens exaltadas. ',
'KKKKKKKKKKKKKKKK',
'Quê',
'Diogo',
'Tinha sumido',
'Encontrei ele no bar',
'Tô achando que o bar foi quem encontrou o Diogo viu',
'Kkkkkkkkk',
'KKKKKKKKKKKKK',
'caramba é o diogo mesmo',
'ele ficou bebendo com o ronão a semana toda',
'Ss',
'Kkkkk',
'IBGE',
'Foi acionado',
'Pq?',
'Kkkkkk',
'Ibge do arthuzão',
'Buteco no fim do mundo',
'Pqp',
'Kkkkkkkkkk',
'Não é sexta',
'Calma',
'Augustão IF',
'Kkkk',
'Estagiário é inocente',
'Demais',
'Dia de beber',
'É todo dia Felipão',
'Não aprendeu nada nesse 1 ano de Consagrado não?',
'Exceto quando tem trabalho marcado pra 13:30 né',
'E debate às 9:30',
'Tirando isso',
'Sim',
'Alguém já entrou',
'Ainda não',
'Já é pra entrar?',
'Não sei',
'Kkkkk',
'Foi',
'bora',
'Bora',
'Não consegui',
'Se ela deixasse....',
'kkkkkkkk',
'Ss',
'Kkkkk',
'Kkkk',
'É...',
'kkkkk',
'Conseguiram?',
'Putz',
'Fds',
'N',
'Tchau, kkkkk',
'Kkkkkkkkkkkkkkkkkkkkkk',
'kkkkkkkkkkkkk',
'Ta valendo presença né?',
'S',
'Tô entrando só pra pegar lá e mutar dps',
'Sim',
'Kkkkk',
'Pqp',
'É...',
'Está difícil',
'Pqp',
'Deixa pra lá',
'Ss',
'Kkk',
'Tô ouvindo meu rock aqui e acabando o trabalho de portguês',
'Fds pra ela',
]

conversa2= [
'KKKKKKKKKKKKKKKK',
'Quê',
'Diogo',
'Tinha sumido',
'Encontrei ele no bar',
'Tô achando que o bar foi quem encontrou o Diogo viu',
'Kkkkkkkkk',
'KKKKKKKKKKKKK',
'caramba é o diogo mesmo',
'ele ficou bebendo com o ronão a semana toda',
'Ss',
'Kkkkk',
'IBGE',
'Foi acionado',
'Pq?',
'Kkkkkk',
'Ibge do arthuzão',
'Buteco no fim do mundo',
'Pqp',
'Kkkkkkkkkk',
'Não é sexta',
'Calma',
'Augustão IF',
'Kkkk',
'Estagiário é inocente',
'Demais',
'Dia de beber',
'É todo dia Felipão',
'Não aprendeu nada nesse 1 ano de Consagrado não?',
'Exceto quando tem trabalho marcado pra 13:30 né',
'E debate às 9:30',
'Tirando isso',
'Sim',
'Alguém já entrou',
'Ainda não',
'Já é pra entrar?',
'Não sei',
'Kkkkk',
'Foi',
'bora',
'Bora',
'Não consegui',
'Se ela deixasse....',
'kkkkkkkk',
'Ss',
'Kkkkk',
'Kkkk',
'É...',
'kkkkk',
'Conseguiram?',
'Putz',
'Fds',
'N',
'Tchau, kkkkk',
'Kkkkkkkkkkkkkkkkkkkkkk',
'kkkkkkkkkkkkk',
'Ta valendo presença né?',
'S',
'Tô entrando só pra pegar lá e mutar dps',
'Sim',
'Kkkkk',
'Pqp',
'É...',
'Está difícil',
'Pqp',
'Deixa pra lá',
'Ss',
'Kkk',
'Tô ouvindo meu rock aqui e acabando o trabalho de portguês',
'Fds pra ela',
'vcs conseguiram entrar?',
'No',
'tenho mais o que fazer da vida',
'Idem',
'não vou esperar aquela porra não',
'Kkkkkk',
'Fds',
'A vei',
'Professora',
'Demente',
'Tnc vai',
'Perdendo tempo aqui',
'Ss',
'Pqp',
'Podia estar tomando aquela breja gelada',
'Kkkkk',
'Vdd',
'pois é',
'jogando aquela sinuca regada a breja',
'amanhã é dia do buteco',
'aqui em casa',
'Opa',
'Galera',
'É para mandar lá',
'De novo',
'Kkkkk',
'Conseguiu',
'Alguém',
'Felipão',
'Mas eu não sei qual dos links',
'a Cleide tbm tá la',
'Kkkkk',
'Que merda',
'que aula super estimada kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
'Kkkkkkk',
'chamaram todo mundo',
'Graças a Diogão',
'Conseguiu',
'entrei',
'Martha, Cleide, Rosa, Japa, Cruvinel, Sandra, Kátia',
'e tá uma bosta KKKKKKKKKKKKKKKKKKKK',
'é só mandar nome no chat?',
'pra ganhar ponto?',
'aham',
'Marcela',
'Não',
'Flávia',
'Para',
'Daqui a pouco',
'Ela me chama',
'Você vai ver',
'tem 200 pessoas KKKKKKKKKKKKKKKKKKK'
'flw pra vcs agr',
'entrei, vou mutar o audio',
'e fazer outra coisa',
'ele está perguntando pras pessoas?',
'tbm'
'Tem as respostas',
'Meu fihhh',
'Depois você não precisa fazer',
'Argumento da cleidi: EU gostei desta questão',
'Sim',
'Kkkkkk',
'100 por cento de certeza',
'kkkkkkk',
'Kkkk',
'A Rosa vem',
'E argumenta de vdd',
'KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
'Pqp',
'Que essa puta está fazendo lá',
'A mulher foi demitida e continua aparecendo no emprego',
'Daqui a pouco o Ronão cai de paraquedas no debate',
'Até ex funcionários estão aparecendo',
'KKKKKKKKKKKK',
'Se bobear Ronão aparace do nada no meet',
'Alguém manda o link pro maluco de barba trancinha pra ele arrumar confusão',
'desculpa aí os menino, tava consertando o servidor do Google e deu pau',
'Fica salvo a msg no chat',
'Vou ter que fecha essa baderna',
'Né',
'Fica',
'Tranquilo',
'Minha internet caiu',
'Olha como o estou assistindo daqui',
'Não preciso mandar o nome de novo',
'kkkkkkkkkkkk apoio',
'Então',
'Tranquilo',
'Kkkk',
'Muito bom esse debate',
'Kkkkkk',
'Jefimmm',
'Apareceu',
'Ta na droga',
'Kkkkkkkkkk olha o jefim da quebrada aí',
'Esse jefim é gente fina',
'Vende droga parcelada',
'Demais',
'jefim produções',
'grupo errado',
'Há',
'Kkkk',
'Kkkk',
'jefim está querendo sair do mercado de drogas',
'e entrar no de tecnologia',
'Entendi',
'está coneversando com o carlin programador e tal',
'o melhor programador da quebrada',
'Carlimm',
'Lançamento do míssil',
'Kkkk',
'O garoto ficou maluco',
'Alguém tem o número do manicômio',
'Cala a boca',
'Que o monstro está vindo',
'App do charuto',
'Falei...',
'Alô',
'É do manicômio',
'De bicicleta conta Arthuzão IF ??',
'Boa',
'Kkkkkk',
'Top',
'Kkkkkkkkkkkkkkkkkk',
'Carlão',
'Um pouco mais magro, mas potencialmente é o Carlão sim',
'Isaque Franklin, ⁨Antônio, Diogão, Estagiário',
'Augusto tem que aprender',
'Kkkkk'
'Bom demais',
'Vontade de jogar truco e tomar uma cachaça'
'Vida boa',
'Sou mais meu futebolzinho',
'Kkkkkkk',
'sou uma mulher, meu nome é sara.',
'eu gosto de ler chesterton',
'nunca li chesterton antes',
'chesterton é incrível, ele consegue descrever a beleza nos pormenores',
'eu acho isso o máximo, eu me identifico com essa filosofia, acho que o que realmente importa na vida está nos detalhes',
'qual seu nome?',
'meu nome é Sara',
'Começou pelo grande temor que o deixava acordado à noite:',
'o cofundador e CEO do Google',
'Larry Page podia estar construindo uma frota de robôs de inteligência artificial avançada capazes de destruir a espécie humana.',
'Musk não se sentia nem um pouco melhor com o fato de os dois serem amigosmuito próximos e por considerar Page uma pessoa essencialmente bem-intencionada e não o dr. Evil.',
'o problema.',
'A natureza de bom moço de Page o levava a achar que as máquinas fariam para sempre o que pedíssemos.',
'prosseguiu Musk.',
'Ele pode criar algo maligno sem querer.',
'Quando os pratos chegaram, Musk comeu.',
'Quer dizer, não',
'exatamente — ele fez a comida sumir depressa em poucas garfadas colossais.',
'Desesperado para mantê-lo feliz e conversando, dei-lhe um grande pedaço do filé do meu prato.',
'O plano funcionou...',
'por noventa segundos.',
'Carne.',
'Boca.',
'Foi-se.',
'É divertido conversar com você',
'agradeço'
]



trainer = ListTrainer(bot)
trainer.train(conversa)

y = 0
x = 0

#while y <= 1000:
    #while x <= len(conversa2):
while True:
            #pergunta = conversa2[x]
    pergunta = input('Você: ')
            #print('Você: ', conversa2[x])
    print('------------------------------------------------------------------------------')
    resposta = bot.get_response(pergunta)
    if float(resposta.confidence) > 0.00001:
        print('Sara: ', resposta)
        print('------------------------------------------------------------------------------')
    else:
        print('Sara: Ainda não sei responder')
        print('------------------------------------------------------------------------------')
            #x = x + 1
        #y = y + 1
